Add click events in Google Analytics
elevatte/elevatte.github.io pull request #33
Opened 2024-07-08 19:28 UTC by riccileonardo

## ✍🏻 Descrição
Este PR adiciona eventos de clique para todos os elementos na landing page, com o objetivo de melhorar o rastreamento dos usuários através do Google Analytics.

## 🧪 Como testar
Para testar, precisamos subir em produção, e dentro do GA ir em relatórios, quando clicarmos nos botões dentro da landing page, obrigatoriamente precisa aparecer o evento.

Link para o painel:
[Link para o relatório de eventos dentro do GA](https://analytics.google.com/analytics/web/#/a176083311p447231843/admin/events/overview?params=_r..layout.pageNumber%3D0%26_u..pageSize%3D25)

## 💎 O que a PR faz
Ele analisa o evento, ou seja click em botões, logo de parceiros, links e cards de notícias.
Quando é feito essa CTA, ele chama helper que dispara o evento.

2024-07-08 19:35 UTC, rafaelricci requested changes

2024-07-08 19:35 UTC, rafaelricci commented on src/App.js
> +          <Route path="/" element={< ElevatteLandingPage />} />
Não tem necessidade desse espaço

```suggestion
          <Route path="/" element={<ElevatteLandingPage />} />
```

2024-07-08 19:55 UTC, rafaelricci commented on src/helpers/GoogleAnalytics.js
> +function initializeAnalytics() {
Acredito que essa função seja `export` também.

Ela sendo exportavel você pode inicializar ela no `App.js` e não vai ter a necessidade de inicializar todas as vezes que chamar o metodo de `click` ou `pageView`.

Desta forma você refatora os metodos "send's".

Fez sentido?

2024-07-08 20:01 UTC, rafaelricci commented on src/App.js
> +      {window.location.hostname === 'elevatte.me' && sendPageView()}
Essa lógica do `window.location.hostname === 'elevatte.me'` pode ser refatorada e jogada para o helper e aplicada para todo tipo de evento. 

Fez sentido?

2024-07-09 18:12 UTC, riccileonardo commented on src/helpers/GoogleAnalytics.js
> +function initializeAnalytics() {
![image](https://github.com/elevatte/elevatte.github.io/assets/122654112/c9481008-62cf-44a9-a083-5a36e36af464)
Rafa na sua sugestão, eu posso remover a inicialização das funções de `sendPageView` e `sendClick`.

2024-07-09 18:12 UTC, riccileonardo commented on src/helpers/GoogleAnalytics.js
> +function initializeAnalytics() {
E nisso eu importo ela na app.js?

2024-07-10 19:49 UTC, rafaelricci approved these changes

2024-07-12 17:50 UTC, merged